### PR TITLE
Change option attribute to items in select, multiselect, radio controls

### LINKED ISSUE #195: Multi-Select Control: "Undefined index: items" from rest-api.php
Hello,

I tested the new Multi-Select control implementation. Unfortunately I receive an error 
**"Notice: Undefined index: items"** from the Rest API. (See full error output below!)

### Field config:

**Choices:**

```
news : News
info : Info
update : Update
```

**Default value:**

`news`

### Error output

```
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
{"rendered":"\r\n<h2>Just a box!<\/h2>\r\n\r\npre>\r\nbox-type:\r\narray(1) {\n  [0]=>\n  string(4) \"info\"\n}\n<\/pre>"}
```

### PR DESCRIPTION
**Pull request by lukecarbis**
Resolves #195 .

@greenphp, can you please test that this resolves the issue?

Note that you'll have to remove the "problem block" from current posts, and resave the block itself. This won't fix existing content, but it should stop it from happening on new content.

### CODE REVIEW

**Comment by camya** [comment]
@lukecarbis I switched to `bugfix/195-multiselect-rest-api-error`, but still get the error.

The line 1121 outputs the notice. (The line number in the screenshot is wrong, it's still line 1121)
`$is_valid = rest_validate_value_from_schema( $v, $args['items'], $param . '[' . $index . ']' );` 
It still misses the key 'items' in the $args array.

image

**Comment by lukecarbis** [comment]
@greenphp Can you please confirm that you still get this error after resaving the block, and inserting it into a new post?

**Comment by camya** [comment]
Yes, I re-saved the block and created a complete new post with this updated post. I still get the error nevertheless.

**Comment by RobStino** [comment]
Hey @lukecarbis and @greenphp 
I tested this as well and I'm still observing the same `Undefined index` error.

Testing steps
1. on develop branch ( to check I can replicate the initial issue)
2. npm run build
3. new block with a multi-select
4. New post. Add new block
5. Error confirmed on front end
6. Switch to this PR branch
7. npm run build
8. New block with a multi-select
9. New post. Add new block
10. Still getting error on front end
image

**Comment by lukecarbis** [comment]
I'll try a different approach.

**Pull request closed without merging**
