### PR TITLE
Feature/colour

### LINKED ISSUE #32: "Colour" control type

### PR DESCRIPTION
**Pull request by lukecarbis**
An alternate approach to a colour picker control.

Closes #201.
Resolves #32.

### CODE REVIEW

**Comment by lukecarbis** [comment]
Here's a template you can use to test the colour picker (just change the field name on line 1 to match your field): https://gist.github.com/lukecarbis/28d70ece69ee97adfbf769011301a573

**Comment by RobStino** [comment]
I'm still QA testing, but noticed the following. Mostly discussed in our call earlier.
- The text input for the text field should not read only. I'm guessing that any pasted/typed input will mean the control will have to recognise what's being input.
- The hashed background on the colour indicator for Alpha colour types
- Hover state you mentioned isn't working
- The Colour indicator circle size isn't the same height as the text input. Looks funky
- Need to style the colour indicator for the inspector

**Comment by lukecarbis** [comment]
Okay – I've updated the PR with those fixes. A couple of notes:

- The colour indicator circle is now 28px with 1px margin on top and bottom (total 30px), whereas the text input is 30px high. This colour indicator height matches the other colour circles in Gutenberg.
- Know unfixable (for now) issue: changing the colour in the colour picker, _then_ in the text input, the colour circle doesn't update after the text changes
- This also fixes an issue where error'ed fields (such as bad URLs or Emails) in the sidebar weren't receiving the correct red border styles

**Comment by RobStino** [comment]
Tested and confirming:
- Checked background looks great!
- No more read only. Nice!
- Sidebar styling looks good

Re the colour indicator circle placement in the editor, is it possible to have it vertically aligned with the center of the text field?

I'm still seeing this _No's_ in the editor and front end as discussed last night. I forgot to add it as a comment here in the PR, so adding it here now.

**Comment by lukecarbis** [comment]
@RobStino It should be vertically aligned already – screenshot it for me?

Is the "No's" issue a problem with this PR or is it on `develop`?

**Comment by RobStino** [comment]
Hey @lukecarbis 
It's vertically aligned to the top currently. 
image

Checked and the "No's" issue is only on this PR branch.

**Comment by RobStino** [comment]
@luke I adjusted that margin further so it's vertically centered.
image
Check it over and merge when you're ready. I've reviewed/approved.

**Review by RobStino — APPROVED** [review]
Looks good to me

**Pull request merged**
