### PR TITLE
More Controls

### LINKED ISSUE #10: "Select" control type
This should introduce the concept of control options for custom fields. Potentially, abstract fields out further to have a `field type` interface / abstract, with each `field type` (text, texture, select) implemented as its own class.

- Choices

### LINKED ISSUE #11: "Checkbox" control type
- Choices

### LINKED ISSUE #12: "Number" control type
- Minimum Value
- Maximum Value
- Step Size

### LINKED ISSUE #16: "Radio" control type
- Choices

### LINKED ISSUE #17: Toggle "True / False" Control Type

### PR DESCRIPTION
**Pull request by lukecarbis**
@rheinardkorf The admin UI is working and saving properly, but there's an error when adding the block in the Gutenberg editor, which I can't figure out. Could you take a look for me?

Here's the JSON that gets saved:

```
      "bar": {
        "name": "bar",
        "label": "Bar",
        "control": "select",
        "location": "editor",
        "order": 2,
        "help": "Field instructions go here.",
        "options": {
          "mon": "Monday",
          "tue": "Tuesday",
          "wed": "Wednesday",
          "thu": "Thursday",
          "fri": "Friday"
        },
        "default": [
          "mon",
          "wed"
        ],
        "multiple": true
      }
```

Resolves #10, Resolves #11, Resolves #12, Resolves #16, Resolves #17

### CODE REVIEW

**Comment by lukecarbis** [comment]
screen shot 2018-08-12 at 12 34 47 am

**Comment by rheinardkorf** [comment]
Argh... found the error.
@lukecarbis ... see #10 for the correct json required for the select control.  (you'll see samples for each of the controls).

The expected format for the options are...
```
"options": [
          {
            "label": "Option 1",
            "value": "option-1"
          },
          {
            "label": "Option 2",
            "value": "option-2"
          },
          {
            "label": "Option 3",
            "value": "option-3"
          },
          {
            "label": "Option 4",
            "value": "option-4"
          }
        ],
```

**Comment by lukecarbis** [comment]
This PR is now ready for review. It add the following controls:
- Select
- Range
- Toggle
- Radio
- Checkbox

Unfortunately, I can't test them in the Gutenberg editor, since I'm coming up against an error when I add a block containing a toggle, radio, checkbox, or range control. This error happens whether using a custom `blocks.json` file to define the block, or defining it with the ACB Block Editor UI. It also happens on develop with a `blocks.json` file, so it's not specific to this PR. Regardless, I recommending not merging this PR until we've resolved that.

**Comment by lukecarbis** [comment]
Figured out that the error we've been getting is a browser issue (Safari is known to not play nicely with Gutenberg). I recommend reviewing and merging this PR in Chrome, and creating a seperate issue for Safari support.

**Review by rheinardkorf — CHANGES_REQUESTED** [review]
@lukecarbis can you please run this through WPCS `WordPress` standard?  There are some WPCS issues that needs fixing before I merge. Other than that its looking good.

**Review by rheinardkorf — APPROVED** [review]

**Pull request merged**
