### PR TITLE
Review escaping functions according to Issue #60

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Solves Issue #60

### CODE REVIEW

**Comment by rheinardkorf** [comment]
@pedro-mendonca awesome! were there any others you found or are these the only ones?

**Comment by pedro-mendonca** [comment]
@rheinardkorf I've made a search on all the code for `echo` and `esc_` within attributes and only found these.

**Review by rheinardkorf — APPROVED** [review]

**Comment by pedro-mendonca** [comment]
One thing I found inconsistent was the use of either `echo esc_attr` or `esc_attr_e`. But that wasn't the intent of this PR so I didn't touch it :)

**Comment by lukecarbis** [comment]
I just went through and checked every instance of `esc_attr`, `esc_attr_e`, `esc_html`, and `esc_html_e`, and they're all correct. 

@pedro-mendonca  the `_e` functions are used for translatable text.

**Comment by pedro-mendonca** [comment]
@lukecarbis I meant that I've found cases where it's used `echo esc_attr` and others where its `esc_attr_e`, that is basically the same. Still, I didn't change those.

You can see an example in the commitdiff of this PR.

**Pull request merged**
