### PR TITLE
For the textarea control, use a textarea for the default setting

### PR DESCRIPTION
**Pull request by kienstra**
* Before, the `Textarea` control had an `<input>` for the 'Default Value' setting
* Now, it has a `<textarea>` for the default value
* This is in response to a WordPress.org [support topic](https://wordpress.org/support/topic/default-value-for-textarea-not-accepting-multiple-lines/#post-11802107)
* It looks to be backwards-compatible with the previous default value saved in the `<input>`, but more testing would be appreciated

# Edit Block UI

textarea-default-value

# Block Editor UI

ta-field

Maybe it'd make sense to also make the 'placeholder' setting a `<textarea>`. But I'm not sure how many people need a multiple-line placeholder.

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @lukecarbis,
Could you please review this? Thanks!

**Comment by kienstra** [comment]
**Request For Review**

Hi @lukecarbis,
Could you please review this? Thanks!

**Comment by kienstra** [comment]
Note to self: ping `@lewisself` on the WordPress.org [support topic](https://wordpress.org/support/topic/default-value-for-textarea-not-accepting-multiple-lines/#post-11802107) he raised if and when this PR is released on WordPress.org.

**Review by lukecarbis — APPROVED** [review]
Looks and works good!

**Comment by kienstra** [comment]
@lukecarbis, thanks a lot for reviewing this.

Is it alright to merge this in before the release tomorrow?

**Comment by lukecarbis** [comment]
Absolutely.

**Comment by kienstra** [comment]
Thanks!

**Pull request merged**
