### PR TITLE
Workaround for users with different Site Address and WordPress URL settings

### PR DESCRIPTION
**Pull request by lukecarbis**
@mattkevan I couldn't manage to replicate #270 exactly, but I did replicate the error you referenced. Can you check whether this fix resolves the problem you reported?

### CODE REVIEW

**Comment by lukecarbis** [comment]
@kienstra Even if this doesn't resolve #270, it does resolve a problem for users with a different Site URL and Home URL. See https://github.com/WordPress/gutenberg/issues/1761.

**Comment by kienstra** [comment]
**Looks Good**
*Question About Where This Should Be Fixed*

Hi @lukecarbis,
The code looks good, but do you think Block Lab is the right place to fix this?

You understand this issue better than I do. But in that issue you linked to, it looks like this affects the block editor and the REST API, not just Block Lab: https://github.com/WordPress/gutenberg/issues/1761#issuecomment-387912777

>Given the impact of this issue was a deliberate design decision for the REST API...

It'd be interesting to see how this works for @mattKevan, or if he had this issue with the block editor in general, or only this plugin.

**Comment by kienstra** [comment]
I couldn't reproduce the issue when I set the WordPress Address (home) to a different URL than the Site Address (siteurl):

different-from-wp-address

With the `develop` branch checked out, adding blocks worked fine:

diff-site-url

Maybe there's a better way to reproduce this issue, though.

**Review by kienstra — COMMENTED** [review]
I couldn't reproduce the issue when I set the WordPress Address (home) to a different URL than the Site Address (siteurl):

different-from-wp-address

With the `develop` branch checked out, adding blocks worked fine:

diff-site-url

Maybe there's a better way to reproduce this issue, though.

**Comment by lukecarbis** [comment]
@kienstra I agree that block lab might not be the right place for this fix. 

Try reproducing by changing the domain in the URL (not just the path).

**Comment by lukecarbis** [comment]
Given that this is an issue that affects all dynamic blocks (in fact, any block that makes a REST API call), I'm going to suggest we allow the fix to come from the Gutenberg team.

**Pull request closed without merging**
