### PR TITLE
Add `blocklab_get_block_attributes` filter

### LINKED ISSUE #360: Add filter to `get_block_attributes` to allow third-party attributes
I've created [EditorsKit](https://wordpress.org/plugins/block-options/) plugin to extend Gutenberg editor and blocks. Using the plugin together with Block Lab is logging this error `{"code":"rest_invalid_param","message":"Invalid parameter(s): attributes","data":{"status":400,"params":{"attributes":"editorskit is not a valid property of Object."}}}` since the attribute was registered via JS. Is it possible to add PHP filter on `get_block_attributes` function for me to add the missing attribute and prevent the error? Thanks!

### PR DESCRIPTION
**Pull request by phpbits**
Closes #360

### CODE REVIEW

**Comment by lukecarbis** [comment]
Great! Thanks @phpbits. I'll merge it into a separate branch before merging into develop, just to change the filter name:
`blocklab_get_block_attributes` > `block_lab_get_block_attributes`

**Comment by phpbits** [comment]
@lukecarbis Thanks a lot! I'm really glad that you are open to extend Block Lab for third-party plugin compatibilities :) Let me know how it goes and will test it out when ready. Thanks again!

**Comment by lukecarbis** [comment]
@phpbits Absolutely! If there's more we can do, please let me know. This change will be included in the next release.

**Comment by phpbits** [comment]
Thanks again @lukecarbis! Will definitely let you know if I encounter another one. Cheers!

**Pull request merged**
