### PR TITLE
📧Ⓜ️🧿🏑🕴️💰

### LINKED ISSUE #97: Special characters in block title and description
Special characters aren't handled well in the Gutenberg editor.

### LINKED ISSUE #126: Special character in title causes no meta data to be saved
1. Create a new Block with the title "Luke's Block" (use an apostrophe)
2. Add fields (you're going to loose these when you publish)
3. Publish
4. 😿

### PR DESCRIPTION
**Pull request by lukecarbis**
Fixes all special character issues when creating a new block.

Resolves #126 
Resolves #97

### CODE REVIEW

**Comment by RobStino** [comment]
Tested this. Still seeing issues.
- Pulled latest and switch to the PR branch.
- `NPM run build`
- Created a block with an apostrophe in the title, added fields, and published. Success! See [126](https://github.com/getblocklab/block-lab/issues/126)
- Changed the title to include emojis. See [97](https://github.com/getblocklab/block-lab/issues/97)
- Published
- Lost all meta :(

As an aside, the process of changing the title also reset the slug. This is expected behaviour, but I'm not so sure we should keep this. If I have a block that I've been using and want to change the title. The slug changing automatically is a bit of a pain. Will create an enhancement ticket for this.

**Comment by lukecarbis** [comment]
@RobStino Using those steps, and it works for me! Am I missing something? https://drive.google.com/file/d/19rhojCispqZVk7Gj4nKHHv9H_HoHdB8G/view

**Comment by RobStino** [comment]
@lukecarbis Ahh. OK. So I tested with _only_ special characters in the title. That's what broke it. See the video -> https://d.pr/v/T4HHFT

**Comment by lukecarbis** [comment]
@RobStino Great catch. Try now!

**Comment by RobStino** [comment]
Cool. Good fix.
For clarity. Empty title blocks, or special character only title blocks, are given a slug of `block-{post-id}`
This works well!

**Review by RobStino — APPROVED** [review]

**Pull request merged**
