### PR TITLE
Set the posts_per_page to 100

### PR DESCRIPTION
**Pull request by kienstra**
This should help the case that Block Lab performs well, and is scalable (#485).

The `-1` value probably wouldn't get past a VIP review. 

Ideally, people creating more than 100 blocks in the 'Edit Block' UI would use the PHP API.

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @lukecarbis,
Hope you had a great weekend.

Sorry, I still owe you a review for #486.

When you have a chance, could you please review this? It should help our case that Block Lab performs well and scales (#485).

**Review by lukecarbis — APPROVED** [review]
Looks good to me.

**Comment by lukecarbis** [comment]
@kienstra Maybe consider adding a comment on that line to explain why it's `100`, not `-1`.

**Comment by kienstra** [comment]
Sure, that's a good point.

**Pull request merged**
